#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jan 26 03:40:01 EST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=\u00A7aretrovision_v1.80.1.zip
