#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jan 25 01:18:18 EST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=I Like Vanilla v1.2.1.zip
