#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Mar 18 00:45:33 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=I Like Vanilla v1.3.1.zip
