#Preferences
#Mon Jan 26 16:33:52 EST 2026
action_bar=true
etf_button=true
folder_pack=true
options=false
original_screen=false
respackopts_button=true
toggle_incompatible=false
vtd_button=true
vtd_edit_button=true
