#Preferences
#Sun Jan 25 00:27:44 EST 2026
action_bar=true
etf_button=true
folder_pack=true
options=true
original_screen=false
respackopts_button=true
toggle_incompatible=false
vtd_button=true
vtd_edit_button=true
