#Preferences
#Wed Mar 25 18:57:03 EDT 2026
action_bar=true
etf_button=true
folder_pack=true
options=false
original_screen=false
polytone_button=false
respackopts_button=true
toggle_incompatible=false
